from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch

from archie.policy import create_objective_selector


def rounded(values):
    return json.loads(json.dumps(values, separators=(",", ":")), parse_float=lambda value: round(float(value), 7))


def main() -> None:
    parser = argparse.ArgumentParser(description="Export Objective Selector V0 for Bedrock JavaScript")
    parser.add_argument("--checkpoint", type=Path, default=Path("checkpoints/objective-selector-v0.pt"))
    parser.add_argument("--output", type=Path, default=Path("bedrock/archie_v0/scripts/policy_weights.js"))
    args = parser.parse_args()

    model = create_objective_selector()
    saved = torch.load(args.checkpoint, map_location="cpu", weights_only=True)
    model.load_state_dict(saved["state_dict"])
    layers = []
    for index in (0, 2, 4):
        layer = model[index]
        layers.append({
            "weights": rounded(layer.weight.detach().tolist()),
            "bias": rounded(layer.bias.detach().tolist()),
        })
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "// Generated by scripts/export_policy_for_bedrock.py\n"
        "export const OBJECTIVE_SELECTOR_V0 = "
        + json.dumps({"layers": layers}, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(args.output)


if __name__ == "__main__":
    main()
